### ISSUE TITLE
Why do you choose Spring Native for your app

### ISSUE THREAD

**Issue by HelloTo4x** [fishandsheep/spring-native-demo#1]
Hi, i am reading your project, but i have a question, why do u choose Spring Native for your app instead of Quarkus of other framework for build with GraalVM. Can u tell me the pros and cons of Spring Native ? When should we use it instead of other framewoks ?

**Comment by fishandsheep** [comment]
@HelloTo4x 你好，我用中文回复了
1. 选择使用Spring Native 是因为我真正的项目使用了 SpringBoot ,迁移成 Quarkus 成本太高了
2. 个人觉得 SpringNative 的最大的优点可是使用Spring繁荣的生态，缺点也就是相当于“负重前行”，暂时不能很好的兼容GraalVM
3. 如果是新项目，又想最大限度的使用Java的云原生，建议使用Quarkus

感谢回复，感兴趣的话可以看看周志明老师关于[Graal VM:云原生时代的Java](https://www.bilibili.com/video/BV1dV411r7ZC?spm_id_from=333.999.0.0&vd_source=0288f043cc6c07fc3117619f74889fe6)的分享

**Comment by fishandsheep** [comment]
换框架要重写代码，对Quarkus不熟悉。。。

这个项目是因为我想打包成一个完全 “static” 的镜像，如果是只想做一个“尽可能static”的镜像，SpringNative 和 Quarkus 都支持

参考 [Build Mostly Static Native Image](https://www.graalvm.org/22.1/reference-manual/native-image/StaticImages/)
